- src/constants/token/pancakeswap.json
Added dice information for listing
> add dice information

- package.json
- src/components/Modal/index.tsx
- src/components/TransactionConfirmationModal/index.tsx
- yarn.lock
> fix: disable modal gesture

- listing.md
> fix linting errors

- src/components/Header/Nav.tsx
> update voting route

- README.md
- src/utils/translateTextHelpers.ts
- Updated the readme to include a section on how to update Translations within the codebase
- Updated the `translateTextHelpers` to be able to handle variable values (like `%token%` in Crowdin)
That's it! 🚀
> Localistation added to readme and translation logic upgraded to handle variables

- src/state/index.ts
- src/state/user/hooks.tsx
- src/utils/theme.ts
> fix: add theme cache

- src/constants/token/pancakeswap.json
> change CTK decimals from 18 to 6

- src/constants/token/pancakeswap.json
> add QUSD and KUN

- .github/CODEOWNERS
- .github/pull_request_template.md
> Update github config

- src/constants/token/pancakeswap.json
Build was failing.
Run Prettier on config file.
> fix: Config file format

- src/components/SearchModal/CurrencyList.tsx
- src/components/SearchModal/CurrencySearch.tsx
Fixes currency selector in dark mode.
> fix: Currency selector in dark mode

- src/components/TokenWarningModal/index.tsx
Fixes the the TokenWarningModal in dark mode.
> fix(style): TokenWarningModal in dark mode

- src/components/Shared/Type.tsx
- src/components/swap/SwapModalHeader.tsx
This should fix most of the text issues. I just replaced the all the TYPES with using the corresponding values using `<Text />`
> fix(style): TYPE now uses Text component

- package.json
- src/components/Menu/index.tsx
- yarn.lock
Upgrades UI Kit to support Binance Chain Wallet
> feat: BSC Support

- .github/workflows/tests.yaml
Fix the CI environment for all Actions; some tests are still failing but it is no longer related to Actions being outdated.
Added comments about what changes are relevant here.
- Fix a missing env variable in `unit-tests` action (still fail, but not run correctly).
- Upgrade GitHub Actions version.
- Naming and cleaning of steps for easier maintenance.
> fix: GitHub Actions

- package.json
- src/components/Menu/config.ts
- yarn.lock
Integrates new UI Kit improvements
> buld: Upgrade UI Kit

- src/components/Menu/index.tsx
- src/hooks/useGetPriceData.ts
> feat: Added Cake price to menu

- src/components/Card/index.tsx
- src/components/Logo/index.tsx
- src/components/Popups/ListUpdatePopup.tsx
- src/components/PositionCard/V1.tsx
- src/components/SearchModal/CommonBases.tsx
- src/components/SearchModal/ListIntroduction.tsx
- src/components/SearchModal/ListSelect.tsx
- src/components/SearchModal/SortButton.tsx
- src/components/SyrupWarningModal/index.tsx
- src/components/TransactionConfirmationModal/TransactionErrorContent.tsx
- src/components/swap/BetterTradeLink.tsx
- src/components/swap/FormattedPriceImpact.tsx
- src/components/swap/SwapRoute.tsx
- src/components/swap/styleds.tsx
- src/pages/AddLiquidity/PoolPriceBar.tsx
- src/pages/AddLiquidity/index.tsx
- src/pages/MigrateV1/MigrateV1Exchange.tsx
- src/pages/Pool/index.tsx
- src/pages/PoolFinder/index.tsx
- src/pages/Swap/index.tsx
Removes instances of `import { Text } from 'rebass'`
> refactor: Remove Rebass Text

- src/components/swap/AdvancedSwapDetailsDropdown.tsx
- src/pages/AppBody.tsx
Fixes issue where tooltips in the details section were not working.
> fix: Tooltips not showing on swap details

- package.json
- src/components/Menu/config.ts
- src/components/Menu/index.tsx
- src/hooks/useGetLocalProfile.ts
- yarn.lock
- Attempts to read local storage for the user's profile
> feat(menu): Profile Avatar

- src/pages/AddLiquidity/redirects.tsx
- src/pages/App.tsx
- src/pages/RemoveLiquidity/redirects.tsx
Fix some redirection issues introduced with #182
> fix: Route redirections

- src/pages/App.tsx
> fix: Arch and pancakes background

- src/constants/localisation/languageCodes.ts
- Remove unused languages
- Update naming of some lang
- Add languages
> chore: update languages

- package.json
- src/hooks/useGetLocalProfile.ts
- yarn.lock
Fixes issue where the local profile information is never retrieved.
> fix: Retrieving local profile

- src/components/ConnectWalletButton/index.tsx
- src/components/Menu/index.tsx
- src/components/ToastListener/index.tsx
- src/hooks/useAuth.ts
- src/hooks/useToast.ts
- src/index.tsx
- src/state/actions.ts
- src/state/hooks.ts
- src/state/index.ts
- src/state/toasts/index.ts
> fix: Add toasts and error messages for wallet connection

- cypress/integration/pool.test.ts
- cypress/integration/remove-liquidity.test.ts
- cypress/integration/send.test.ts
- src/components/SearchModal/CurrencySearch.tsx
- src/hooks/Tokens.ts
- src/hooks/useWrapCallback.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Pool/index.tsx
- src/state/swap/hooks.ts
- src/utils/currencyId.ts
> fix: Fix Swap ETH url to BNB

- src/components/PageHeader/RecentTransactionsModal.tsx
- src/components/PageHeader/SettingsModal.tsx
- src/components/PageHeader/SlippageToleranceSetting.tsx
- src/components/PageHeader/TransactionDeadlineSetting.tsx
- src/components/PageHeader/index.tsx
- src/components/swap/AdvancedSwapDetails.tsx
- src/components/swap/SwapModalFooter.tsx
> fix: Translations in popup modals slippage and recent transactions

- src/state/swap/hooks.ts
> fix: Fix Selecting BNB again after change to something else or select to convert section

- src/constants/token/pancakeswap.json
> fix: JSON formatting

- src/components/Menu/index.tsx
- src/constants/index.ts
- src/hooks/useGetDocumentTitlePrice.ts
- src/hooks/useGetPriceData.ts
Price API update to fetch from subgraph.
> feat: API Tokens endpoint

- src/hooks/LanguageContext.ts
- src/pages/App.tsx
> fix: Apply translation cache when refresh or enter

- src/components/SafeMoonWarningModal/index.tsx
- src/components/SyrupWarningModal/index.tsx
- src/pages/Swap/index.tsx
> Add trading warning for SafeMoon

- src/components/Banner/MigrationV2.tsx
- src/components/VersionBar/index.tsx
- src/pages/App.tsx
- src/pages/Migration/FirstCard.tsx
- src/pages/Migration/SecondCard.tsx
- src/pages/Migration/index.tsx
> feat: Add version bottom bar

- src/components/Menu/config.ts
- src/pages/Migration/index.tsx
**PLEASE DO NOT SUBMIT TOKEN LISTING PULL REQUESTS**
Any Listing PRs or Issues will be closed.
Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
Any Listing issues/PRs will be closed.
---
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-swap-interface/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> chore: Update exchange links

- cypress/integration/pool.test.ts
- src/pages/AddLiquidity/index.tsx
- src/pages/Pool/index.tsx
- src/pages/PoolFinder/index.tsx
To be merged when we want to disable the possibility of adding liquidity on V1.
> chore: Remove add liquidity buttons

- src/components/Menu/config.ts
**PLEASE DO NOT SUBMIT TOKEN LISTING PULL REQUESTS**
Any Listing PRs or Issues will be closed.
Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
Any Listing issues/PRs will be closed.
---
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-swap-interface/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> chore: Migrate tag

- src/components/VersionBar/index.tsx
**PLEASE DO NOT SUBMIT TOKEN LISTING PULL REQUESTS**
Any Listing PRs or Issues will be closed.
Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
Any Listing issues/PRs will be closed.
---
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-swap-interface/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> chore: Remove V2 Discontinued

- src/components/Menu/config.ts
> feat: Remove tag from prediction and change label

- src/components/Menu/config.ts
Reverts pancakeswap/pancake-swap-interface-v1#425
> Revert "feat: Add LIVE tag to IFO"

- src/pages/Swap/index.tsx
**PLEASE DO NOT SUBMIT TOKEN LISTING PULL REQUESTS**
Any Listing PRs or Issues will be closed.
Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform
Any Listing issues/PRs will be closed.
---
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-swap-interface/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> fix: Remove cummies from blacklist
